### ISSUE TITLE
16MB PDF is embedded into the wiki?! The wiki is 240MByte in size

### ISSUE THREAD

**Issue by pmario** [tiddly-gittly/HugeWikiExample#2]
@linonetwo ... I did just run the dev server of this wiki using a completely new install from node.js, vscode, git, npm. 

- At startup it seems to downlaod a 236MByte wiki. ... 
- There is a PRML-Chinese-Edition.pdf .. that is embedded into the wiki. IMO this does not make any sense. It should use _cannoical_uri and lazy-load the thing. I'm using Edge and it does _not display anything. So for me it is broken.
- TemplatePPT.ppt .. causes an error. In don't have PowerPoint in the Sandbox .. Is this one embedded too?
- I also think your "files" folder is in the wrong place. If it is below tiddlers/ it will be embedded into the wiki. 

![image](https://user-images.githubusercontent.com/374655/221406241-4e3a6389-df41-414c-b4ee-410ef895a09b.png)

The TW server does have a filer server option. BUT it needs a `files` directory on the same level as `tiddlers`

From my point of view, with the huge files loaded from a files directory the whole wiki should be sent over the wire in a view seconds ...

**Comment by pmario** [comment]
There is a very big problem with embedded files in TW. They need double the size, because they are base64 encoded 

I did move the big files out of the way and started TW like this. It starts up in about 5 seconds. Down from 30+

```
cd /path/to/HugeWikiExample/
tiddlywiki.cmd +plugins/tiddlywiki/filesystem +plugins/tiddlywiki/tiddlyweb demo --build index
```

```
npm run dev 
```

seems to rebuild the whole thing everytime I run it. ... I want to build once and then only run it for testing. How do you do that?

**Comment by pmario** [comment]
I did a bit more testing ... and the whole tag-pill macro rendering seems to be a huge problem. With an init and the CDDA tiddler open. While rendering the links the parser is started 20000 times. That should not happen. we should hit the cache 20000 times.

**Comment by linonetwo** [comment]
Hi, you can run `npm i` then `npm run dev-html`.

Or `pnpm i` then `pnpm dev-html`.



> * It should use _cannoical_uri and lazy-load the thing

That is true, I forget this. In my personal wiki, I use `lazy-image` that also exclude the PDF. Maybe we can just remove the PDF from this repo. I was trying to reproduce the situation in my personal wiki.

**Comment by linonetwo** [comment]
pnpm dev is good for developing plugin, it auto reload to reveal changes.

**Comment by linonetwo** [comment]
I don't use `files` directory, I usually use lazy-images setup. So I don't need to look at the folder, just drag everything into wiki, like how others use Notion or Obsidian, I think this make it more easy to use.

**Comment by pmario** [comment]
https://github.com/tiddly-gittly/HugeWikiExample/tree/master/demo/tiddlers/Files .. This directory with the huge files is a problem!

Drag & drop import into TW using huge files is a problem. .. IMO it does not matter if it is easier to use, when the whole thing is completely unusable.

**Comment by linonetwo** [comment]
So I always keep eye on lazy loading related things like https://github.com/Jermolene/TiddlyWiki5/pull/7014 

Drag thing into wiki will add metadata to them, while `files` folder may have no?

Anyway, I will comeup with some solution on this in the future.

**Comment by pmario** [comment]
drag & drop import may make a x.pdf and x.pdf.meta but it does _not_ automatically use _cannonical_uri ... So your files are embedded. ... And since I did download 236MByte it did not work. 

So if you want those big files, you can create a "files" directory that is at the same level as the "tiddlers" directory. .. But files have to be stored there manually and _not_ with TW. 

Everything below `tiddlers/` eg: `tiddlers/files`  will be automatically embedded into TW and therefore cause problems. 

I don't know if Saq's file-upload-plugin works with node. I think there are some posts somewhere at talk.tiddlywiki.org

**Comment by linonetwo** [comment]
I will have a try, auto add _cannonical_uri and meta file all together is what I want.

For this repo, I already remove the PDF (or maybe I should enable lazy-image, but I'm going to sleep, GN)
